# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '智能锁' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 智能锁
pod 'YYKit'

  target '智能锁Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '智能锁UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
