platform:ios, '8.0'
inhibit_all_warnings!

target 'HighwayToll_iOS' do
    pod 'TZImagePickerController'
    pod 'AFNetworking', '~> 3.0.4'
    pod 'SDWebImage', '~> 3.8.1' 
    pod 'MJRefresh', '~> 3.1.14.1'
    pod 'Masonry', '~> 1.0.1'
    pod 'IQKeyboardManager', '~> 4.0.3'
    pod 'EGOCache', '~> 2.1.3' 
    pod 'GVUserDefaults', '~> 1.0.2'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'FMDB', '~> 2.6'  
    pod 'MWPhotoBrowser', '~> 2.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'QRCodeGenerator-hicool’
    pod 'MJExtension', '~> 3.0.13'
    pod 'WebViewJavascriptBridge', '~> 5.0.5'
    pod 'DZNEmptyDataSet' 
    pod 'SGQRCode' 
   # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’
   # 集成QQ/QZone/TIM(完整版7.6M)
    pod ‘UMengUShare/Social/QQ'
 # 集成微信(完整版14.4M)
    pod ‘UMengUShare/Social/WeChat'
	# 集成新浪微博(完整版25.3M)
    pod ‘UMengUShare/Social/Sina'
# 集成支付宝
    pod ‘UMengUShare/Social/AlipayShare'
# 集成豆瓣
    pod ‘UMengUShare/Social/Douban'
# 集成腾讯微博
    pod ‘UMengUShare/Social/TencentWeibo'
# 集成邮件
    pod ‘UMengUShare/Social/Email'
end
